sudo: required
dist: trusty
group: edge
language: node_js
node_js:
- 8.6.0
cache:
  directories:
  - node_modules
  - ".tools"
install:
- chmod +x build/*.sh
before_script:
- eval "$(gimme 1.10.2)"
script:
- "./node_modules/.bin/gulp build:cross"
before_deploy:
- mv ./dist/windows/k8sconsole-windows-amd64 ./dist/windows/k8sconsole-windows-amd64.exe
deploy:
  provider: releases
  api_key:
    secure: b72dVBPLZFUoweiv9qz1dbrzP4sXse9EeHn+8TJobh2+pja5E1FGsakuQZPv4MeA/6r6HZQGTACI10j0FzA3a/tuO5WrbhbZnhm1G/G4YsABWAcMjFTCOVKFzfFsG9o1ZRqEKPw8JWps02K4s8xjEmiGLtmNbyGK4oq6B7AawyuO4IzcCeVDabKV3424RNWURVdvAcx+dcFVmsQHKqf+gohqGRNpP0MyQNv551NACrN1IvxsS4nwMTwvc+Q6mV/NogzmjGbVWqlamF+1ZjSXzfeeSXY7s5rP/cRXqo0eGJc7pmn5/yjKI5U2H3nYYzQSJVbU5q9Qa7lfb6IumIigcespgPgY3RjEyczXdPIVdNylsenAXxQzZgtatR/3pIolZSDQCP7u/u9cMzHbylGqwk2Yv0I/Z/p+IfLcvYbM9wjUrR1wfIc6eQtQn4StKgS3QyulJREKHsUj0I70Y/1MQrQ+tvjD/7t19jcmevK7Ma2ieVUHRHASBmIHfqwS4PTm/PS2lwX+SEqpegYIpfybXx6u+jchA5KVklgKYOu14J5pasWzi8gcqAWNRFQgkQjvU4YsBG+jWQX0L7KMCaEgU8Jw6YoScC8HRnDfNHNEDejKP4LYkRUPIZw2h9ZAQJb+VrMdSPr0ta7GYNjY3zCbGNpdJcwQmHK6NeknWh3AWpg=
  file:
    - ./dist/linux/k8sconsole-linux-amd64
    - ./dist/windows/k8sconsole-windows-amd64.exe
    - ./dist/darwin/k8sconsole-darwin-amd64
  skip_cleanup: true
  on:
    repo: hbulpf/k8sconsole
    tags: true
