# Travis CI system configuration file.
#
# Overview on how to customize the configuration is located at:
# http://docs.travis-ci.com/user/customizing-the-build/

sudo: required
dist: trusty
group: edge

# Use Node.js as primary language because Gulp is the build system used in the project.
language: node_js

# Cache downloaded nodejs modules in the node_modules directory for faster build
cache:
  directories:
  - node_modules
  - .tools

before_script:
  # Install dependencies required to setup the build.
  - npm install -g bower
  - npm install -g gulp
  - bower install
script: gulp build
